default_env: &default_env
  stageName: ${self:custom.stage}
  LOG_LEVEL: ${self:custom.log_level}
  DYNAMO_TABLE_NAME: pixy_photos

default_infrastructure: &default_infrastructure
  capacities:
    - table: DynamoDbTable
      read:
        minimum: ${self:provider.dynamodb.ReadCapacityUnits}
        maximum: ${self:provider.dynamodb.MaxReadCapacityUnits}
        usage: 0.75
      write:
        minimum: ${self:provider.dynamodb.WriteCapacityUnits}
        maximum: ${self:provider.dynamodb.MaxWriteCapacityUnits}
        usage: 0.5
  ssm_parameters:
    ListAll:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /apigateway/${self:custom.stage}/${self:custom.service_name}/v${self:custom.api_version}/list_all
        Description: ${self:custom.service_name} api gateway endpoint get
        Type: String
        Value: { "Fn::Join" : ["", ["https://", "${self:provider.gateway.customdomainname}", "/${self:custom.stage}/v${self:custom.api_version}/list_all" ] ] }
  basepathmapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: FalseIfProd
    DependsOn: ApiGatewayStage
    Properties:
      BasePath: ${self:custom.stage}
      DomainName: ${self:provider.gateway.customdomainname}
      Stage: ${self:custom.stage}
      RestApiId:
        Ref: ApiGatewayRestApi
  gateway:
    customdomainname: ${ssm:/apigateway/sodalabs/customdomainname}
    loglevel: INFO

sandbox:
  env:
    <<: *default_env
  <<: *default_infrastructure
  dynamodb:
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5
    MaxReadCapacityUnits: 10
    MaxWriteCapacityUnits: 10
    DeletionPolicy: Delete
